RAPIDS = [
	["Eric Miller"    	 "United States"],
	["Marc Burch"    	 "United States"],
	["Mekeil Williams"    	 "Trinidad and Tobago"],
	["Sam Cronin"    	 "United States"],
	["Dillon Powers"    	 "United States"],
	["Kevin Doyle"    	 "Ireland"],
	["Marco Pappa"    	 "Guatemala"],
	["Shkëlzen Gashi"    	 "Albania"],
	["Jermaine Jones"    	 "United States"],
	["Dominique Badji"    	 "Senegal"],
	["Dillon Serna"    	 "United States"],
	["Zac MacMath"   	 "United States"],
	["Conor Doyle"   	 "United States"],
	["Joseph Greenspan"    	 "United States"],
	["Luis Solignac"    	 "Argentina"],
	["Micheal Azira"    	 "Uganda"],
	["Bobby Burling"    	 "United States"],
	["Sean St Ledge":    	 "Ireland"],
	["Chris Froschauer"    	 "United States"],
	["Jared Watts"    	 "United States"],
	["Axel Sjöberg"    	 "Sweden"],
	["Marlon Hairston"    	 "United States"],
]